# Generated by Django 5.2.8 on 2025-12-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='criada_em',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='user',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
